{{- $secretName := printf "%s-crt" (include "timescaledb.fullname" .) }}
{{- $ca := genCA "timescaledb-ca" 3652 }}
{{- $fullname := include "timescaledb.fullname" . }}
{{- $altNames := list $fullname }}
{{- $cert := genSignedCert $fullname nil $altNames 3652 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "timescaledb.labels" . | nindent 4 }}
    app.kubernetes.io/component: certificates
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  ca.key: {{ $ca.Key  | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key  | b64enc }}
